#### **Tujuan**

<small>
Notebook ini bertujuan untuk memahami karakteristik dari seluruh dataset yang akan digunakan dalam proyek klasifikasi transaksi keuangan.

Tahapan yang dilakukan meliputi:
<br> - Memuat seluruh dataset.
<br> - Melihat ukuran dataset.
<br> - Mengetahui nama kolom.
<br> - Memahami tipe data.
<br> - Memeriksa missing value.
<br> - Memeriksa duplicate data.
<br> - Mengetahui distribusi label pada masing-masing dataset.

Output dari notebook ini adalah pemahaman mengenai kualitas data sehingga dapat ditentukan proses preprocessing yang sesuai.
</small>

In [ ]:
import pandas as pd

C:\Users\ASUS\AppData\Local\Temp\ipykernel_2016\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [54]:
# baca seluruh dataset
df1 = pd.read_csv("../data/raw/train_transaction_dataset.csv")
df2 = pd.read_csv("../data/raw/test_transaction_dataset.csv")
df3 = pd.read_csv("../data/raw/Data_Finance_6_Bulan.csv")
df4 = pd.read_csv("../data/raw/transactions_rows.csv")

In [ ]:
# melihat ukuran dataset
print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)

(5000, 2)
(1000, 2)
(1200, 6)
(20660, 9)

In [ ]:
# melihat nama kolom setiap dataset
print(df1.columns)
print(df2.columns)
print(df3.columns)
print(df4.columns)

Index(['text', 'label'], dtype='object')
Index(['text', 'label'], dtype='object')
Index(['Date', 'Title', 'Amount', 'Type', 'Category', 'Account'], dtype='object')
Index(['id', 'user_id', 'amount', 'type', 'category_id', 'description',
       'transaction_date', 'created_at', 'updated_at'],
      dtype='object')

In [ ]:
# menampilkan 5 data teratas dari setiap dataset 
display(df1.head())

display(df2.head())

display(df3.head())

display(df4.head())

                                                text       label
0  Restaurant payment of Rs 48698 via UPI Ref 388389        food
1  Train ticket purchase of Rs 9244 via UPI Ref 8...      travel
2  Lunch combo purchase of Rs 5797 via UPI Ref 71...        food
3      Mutual fund SIP of Rs 2052 via UPI Ref 198246  investment
4  Train ticket purchase of Rs 33218 via UPI Ref ...      travel

                                                text     label
0     Dinner at hotel of Rs 38122 via UPI Ref 323781      food
1  Electronics store purchase of Rs 7693 via UPI ...  shopping
2       Hotel booking of Rs 36849 via UPI Ref 860973    travel
3  Credit card EMI payment of Rs 35821 via UPI Re...       EMI
4   Uber ride payment of Rs 44997 via UPI Ref 550363    travel

         Date          Title    Amount     Type       Category       Account
0  2025-07-01         Parkir  15907.28  EXPENSE        Tagihan         Gopay
1  2025-07-01  Iuran Bulanan  12793.08  EXPENSE        Tagihan           BCA
2  2025-07-01      Lain-lain    695.24  EXPENSE  Uncategorized         Gopay
3  2025-07-01      Streaming  13464.10  EXPENSE        Hiburan  Dompet Tunai
4  2025-07-01    Warung Nasi  17475.95  EXPENSE  Makan & Minum  Dompet Tunai

,id,user_id,amount,type,category_id,description,transaction_date,created_at,updated_at
0,000050b9-336e-4ad2-88fc-8aae4edb08d5,5dfb98ea-999e-40c5-b107-9f9807844fb0,224000.0,expense,1.0,Belanja sembako,2025-08-17,2025-08-17 00:00:00.206878+00,2025-08-17 00:00:00.206878+00
1,0002abd2-5e74-4806-aa3e-dba235128feb,82e08baf-f1bc-4826-b637-3befb0b2634d,27600.0,expense,1.0,GoFood,2026-01-17,2026-01-17 00:00:00.810971+00,2026-01-17 00:00:00.810971+00
2,000d6f8a-72dd-41b9-b624-f1c35fa69eef,6d681108-6cfd-4e90-aef6-470047b94796,1000.0,expense,1.0,Kopi,2026-05-18,2026-05-18 00:00:00.238444+00,2026-05-18 00:00:00.238444+00
3,000dbf12-06fe-47ba-a6c3-0c7ce7c103c9,6732e5f2-08dd-44fa-98df-aedec94d3043,61000.0,expense,4.0,Shopee,2025-07-08,2025-07-08 00:00:00.579545+00,2025-07-08 00:00:00.579545+00
4,000eeb6b-def0-4784-9163-5a14322d16e0,42637386-fb69-4195-8bb3-aa4f5514b21a,71300.0,NaN,4.0,Elektronik,2025-09-12,2025-09-12 00:00:00.339107+00,2025-09-12 00:00:00.339107+00

In [ ]:
# mengetahui informasi dataset
df1.info()
print("\n")
df2.info()
print("\n")
df3.info()
print("\n")
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    5000 non-null   object
 1   label   5000 non-null   object
dtypes: object(2)
memory usage: 78.3+ KB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    1000 non-null   object
 1   label   1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1200 non-null   object
 1   Title     1200 non-null   object
 2   Amount    1200 non-null   float64
 3   Type      1200 non-null   object
 4   Category  1200 non-null   object
 5   Account   1200 non-null   object
dtypes: float64(1), object(5)
memory usage: 56.4+ KB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20660 entries, 0 to 20659
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                20660 non-null  object
 1   user_id           20660 non-null  object
 2   amount            20660 non-null  float64
 3   type              20645 non-null  object
 4   category_id       19901 non-null  float64
 5   description       20660 non-null  object
 6   transaction_date  20660 non-null  object
 7   created_at        20660 non-null  object
 8   updated_at        20660 non-null  object
dtypes: float64(2), object(7)
memory usage: 1.4+ MB

In [61]:
# memeriksa data yang kosong atau tidak memiliki nilai
print(df1.isnull().sum())
print("\n")
print(df2.isnull().sum())
print("\n")
print(df3.isnull().sum())
print("\n")
print(df4.isnull().sum())

text     0
label    0
dtype: int64


text     0
label    0
dtype: int64


Date        0
Title       0
Amount      0
Type        0
Category    0
Account     0
dtype: int64


id                    0
user_id               0
amount                0
type                 15
category_id         759
description           0
transaction_date      0
created_at            0
updated_at            0
dtype: int64

In [62]:
# memeriksa data yang muncul lebih dari satu kali
print(df1.duplicated().sum())
print("\n")
print(df2.duplicated().sum())
print("\n")
print(df3.duplicated().sum())
print("\n")
print(df4.duplicated().sum())

0


0


0


16

In [67]:
print("Missing Value")
print(df4.isnull().sum())

print("\nDuplicate")
print(df4.duplicated().sum())

Missing Value
id                    0
user_id               0
amount                0
type                 15
category_id         759
description           0
transaction_date      0
created_at            0
updated_at            0
dtype: int64

Duplicate
16

In [70]:
df4 = df4.dropna(subset=["description", "category_id"])

In [71]:
df4 = df4.drop_duplicates()

In [72]:
df4 = df4.reset_index(drop=True)

In [73]:
print("Missing Value")
print(df4.isnull().sum())

print("\nDuplicate")
print(df4.duplicated().sum())

Missing Value
id                  0
user_id             0
amount              0
type                0
category_id         0
description         0
transaction_date    0
created_at          0
updated_at          0
dtype: int64

Duplicate
0

In [74]:
# mengetahui jumlah data pada setiap kategori
df1["label"].value_counts()

label
investment    1055
travel        1005
food           993
shopping       990
EMI            957
Name: count, dtype: int64

In [75]:
df2["label"].value_counts()

label
shopping      230
food          205
EMI           201
travel        192
investment    172
Name: count, dtype: int64

In [76]:
df3["Category"].value_counts()

Category
Uncategorized    232
Makan & Minum    232
Tagihan          219
Hiburan          199
Belanja          198
Goals             68
Gaji              52
Name: count, dtype: int64

In [77]:
df4["category_id"].value_counts()

category_id
1.0    8213
2.0    5056
4.0    2432
3.0    1520
6.0    1463
5.0    1186
Name: count, dtype: int64

#### Kesimpulan

<small>
Berdasarkan hasil analisis data, diperoleh beberapa informasi sebagai berikut:

- Terdapat empat dataset yang akan digunakan.
- Dataset 1 dan Dataset 2 telah memiliki format **text** dan **label** sehingga siap digunakan.
- Dataset 3 dan Dataset 4 masih memiliki struktur kolom yang berbeda sehingga memerlukan proses standarisasi pada tahap preprocessing.
- Missing value dan duplicate data pada Dataset 4 telah diperbaiki (dihapus)
- Distribusi label antar dataset berbeda sehingga diperlukan proses mapping kategori sebelum seluruh dataset digabungkan.

Tahap selanjutnya adalah melakukan preprocessing dan standarisasi seluruh dataset agar memiliki format yang sama sebelum proses pelatihan model dilakukan.
</small>